# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 19.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3
      - name: Setup PostgreSQL
        uses: Harmon758/postgresql-action@v1.0.0
        with:
          # Version of PostgreSQL to use
          postgresql version: latest
          # POSTGRES_DB - name for the default database that is created
          postgresql db: chess
          postgresql user: postgres
          postgresql password: 123
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: node ace test
        env:
          DB_CONNECTION: pg
          PG_HOST: postgres
          PG_PORT: 5432
          PG_USER: postgres
          PG_PASSWORD: 123
          PG_DB_NAME: chess
          APP_KEY: somefakekeythatis>16characters
          NODE_ENV: test
          ASSETS_DRIVER: fake
          SESSION_DRIVER: memory
          CACHE_VIEWS: false
          DRIVE_DISK: local
